### ISSUE TITLE
Running scripts is not longer working on Scrapycloud

### ISSUE THREAD

**Issue by VMRuiz** [scrapinghub/scrapinghub-entrypoint-scrapy#84]
```
Traceback (most recent call last):
  File "/app/python/lib/python3.11/site-packages/sh_scrapy/crawl.py", line 162, in _run_usercode
    _run(args, settings)
  File "/app/python/lib/python3.11/site-packages/sh_scrapy/crawl.py", line 112, in _run
    _run_pkgscript(args)
  File "/app/python/lib/python3.11/site-packages/sh_scrapy/crawl.py", line 142, in _run_pkgscript
    d.run_script(scriptname, {'__name__': '__main__'})
    ^^^^^^^^^^^^
AttributeError: 'PathDistribution' object has no attribute 'run_script'
```

The reason is this change 

https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/blob/f31e458493a8108d59e0e4a7961ee7b4c44881f9/sh_scrapy/crawl.py#L142

It looks like `PathDistribution` from importlib doesn't implements `run_script` method.

**Comment by VMRuiz** [comment]
Hello @wRAR  , Was this solved by https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/pull/85?

**Comment by wRAR** [comment]
I think so.
